# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f95f572bb7d94fbf9f35eab995c818bb86a2354fc5578873f47d5ea39d7756f583267c4a03a316d94b291194fe472a29a87df031557b199349cba4d44aded33d

test:
  secret_key_base: e46d59784d5e941f2ac988fe5eba69acd3b968091366eb2514e724a42f41be5ef24e31cde47c8e25258838fc99582f9842df9663f66d6ebfd6849153b53086de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
